#define PRINT 1
#define EQUAL 2
#define IF_STATEMENT 3
#define ELSE_STATEMENT 4
#define COMPARISON 5
#define COLON 6
#define DEFINITION 7
#define MATH 8
#define IDENTIFIER 9
#define INTEGER 10
#define COMMA 11
#define COMMENT 12
#define EOL 13
#define NESTEDIFLVL1 14
#define NESTEDIFLVL2 15
#define BLANK 16